<a href="https://colab.research.google.com/github/sureshgv/machine-learning-tutorials/blob/main/house_prices_multi_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# YBI foundation
# Get the data from github and run the query

In [2]:
import pandas as pd

In [3]:
# Step 2 : import data
house = pd.read_csv('https://raw.githubusercontent.com/YBIFoundation/Dataset/main/House%20Prices.csv')

In [4]:
house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             21613 non-null  int64
 1   Date           21613 non-null  object
 2   Price          21613 non-null  float64
 3   Bedrooms       21613 non-null  int64
 4   Bathrooms      21613 non-null  float64
 5   Sqft_living    21613 non-null  int64
 6   Sqft_lot       21613 non-null  int64
 7   Floors         21613 non-null  float64
 8   Waterfront     21613 non-null  int64
 9   View           21613 non-null  int64
 10  Condition      21613 non-null  int64
 11  Grade          21613 non-null  int64
 12  Sqft_above     21613 non-null  int64
 13  Sqft_basement  21613 non-null  int64
 14  Yr_built       21613 non-null  int64
 15  Yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  Lat            21613 non-null  float64
 18  Long           21613 non-null  float64
 19  Sqft_living15  21613 non-null  int64
 20  Sqft_lot15     21613 non-null  int64
dtypes: float64(5), int64(15), object(1)
memory usage: 3.5+ MB

In [14]:
house.head()

,ID,Date,Price,Bedrooms,Bathrooms,Sqft_living,Sqft_lot,Floors,Waterfront,View,...,Grade,Sqft_above,Sqft_basement,Yr_built,Yr_renovated,zipcode,Lat,Long,Sqft_living15,Sqft_lot15
0,1,20140916T000000,280000.0,6,3.00,2400,9373,2.0,0,0,...,7,2400,0,1991,0,98002,47.3262,-122.214,2060,7316
1,2,20150422T000000,300000.0,6,3.00,2400,9373,2.0,0,0,...,7,2400,0,1991,0,98002,47.3262,-122.214,2060,7316
2,3,20140508T000000,647500.0,4,1.75,2060,26036,1.0,0,0,...,8,1160,900,1947,0,98166,47.4444,-122.351,2590,21891
3,4,20140811T000000,400000.0,3,1.00,1460,43000,1.0,0,0,...,7,1460,0,1952,0,98166,47.4434,-122.347,2250,20023
4,5,20150401T000000,235000.0,3,1.00,1430,7599,1.5,0,0,...,6,1010,420,1930,0,98168,47.4783,-122.265,1290,10320

In [20]:
from sklearn import preprocessing
label = preprocessing.LabelEncoder()


house['Date']= label.fit_transform(house['Date'])

#house['Date'] = house['Date'].astype(int, )

In [ ]:
house.head()

In [21]:
house.describe()

,ID,Date,Price,Bedrooms,Bathrooms,Sqft_living,Sqft_lot,Floors,Waterfront,View,...,Grade,Sqft_above,Sqft_basement,Yr_built,Yr_renovated,zipcode,Lat,Long,Sqft_living15,Sqft_lot15
count,21613.00000,21613.000000,2.161300e+04,21613.000000,21613.000000,21613.000000,2.161300e+04,21613.000000,21613.000000,21613.000000,...,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000
mean,10807.00000,177.299912,5.401822e+05,3.370842,2.114757,2079.899736,1.510697e+04,1.494309,0.007542,0.234303,...,7.656873,1788.390691,291.509045,1971.005136,84.402258,98077.939805,47.560053,-122.213896,1986.552492,12768.455652
std,6239.28002,109.503659,3.673622e+05,0.930062,0.770163,918.440897,4.142051e+04,0.539989,0.086517,0.766318,...,1.175459,828.090978,442.575043,29.373411,401.679240,53.505026,0.138564,0.140828,685.391304,27304.179631
min,1.00000,0.000000,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,0.000000,0.000000,...,1.000000,290.000000,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000
25%,5404.00000,81.000000,3.219500e+05,3.000000,1.750000,1427.000000,5.040000e+03,1.000000,0.000000,0.000000,...,7.000000,1190.000000,0.000000,1951.000000,0.000000,98033.000000,47.471000,-122.328000,1490.000000,5100.000000
50%,10807.00000,167.000000,4.500000e+05,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,0.000000,0.000000,...,7.000000,1560.000000,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.230000,1840.000000,7620.000000
75%,16210.00000,282.000000,6.450000e+05,4.000000,2.500000,2550.000000,1.068800e+04,2.000000,0.000000,0.000000,...,8.000000,2210.000000,560.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000
max,21613.00000,371.000000,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,1.000000,4.000000,...,13.000000,9410.000000,4820.000000,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000

In [22]:
house.columns

Index(['ID', 'Date', 'Price', 'Bedrooms', 'Bathrooms', 'Sqft_living',
       'Sqft_lot', 'Floors', 'Waterfront', 'View', 'Condition', 'Grade',
       'Sqft_above', 'Sqft_basement', 'Yr_built', 'Yr_renovated', 'zipcode',
       'Lat', 'Long', 'Sqft_living15', 'Sqft_lot15'],
      dtype='object')

In [24]:
y = house['Price']

In [25]:
X = house.drop(['Price'],axis=1)

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size=0.7, random_state=2529)

In [27]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((15129, 20), (6484, 20), (15129,), (6484,))

In [28]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [29]:
# Step 6 : train or fit model
model.fit(X_train,y_train)

LinearRegression()

In [30]:
model.coef_

array([-6.36850558e-01,  1.15236649e+02, -3.11155682e+04,  3.53599803e+04,
        1.09189849e+02,  1.26062276e-01,  1.16989826e+04,  6.47497832e+05,
        5.19556510e+04,  2.72512113e+04,  9.66699194e+04,  7.02063614e+01,
        3.89834872e+01, -2.59375344e+03,  2.19229804e+01, -5.81768616e+02,
        5.99369465e+05, -2.15295709e+05,  2.06000476e+01, -3.85093059e-01])

In [31]:
model.intercept_

6636569.002879852

In [32]:
y_pred = model.predict(X_test)

In [34]:
y_pred[0]

203942.73829308338

In [36]:
y_test.head()

6457     325000.0
15556    207000.0
5595     473000.0
2476     370000.0
13548    359000.0
Name: Price, dtype: float64

In [37]:
X_test.head()
#print(model.predict())

,ID,Date,Bedrooms,Bathrooms,Sqft_living,Sqft_lot,Floors,Waterfront,View,Condition,Grade,Sqft_above,Sqft_basement,Yr_built,Yr_renovated,zipcode,Lat,Long,Sqft_living15,Sqft_lot15
6457,6458,67,2,1.0,810,4080,1.0,0,0,4,6,810,0,1941,0,98126,47.5337,-122.379,1400,4080
15556,15557,335,3,1.0,990,10800,1.0,0,0,4,6,990,0,1959,0,98002,47.2930,-122.215,1060,10364
5595,5596,179,3,1.0,1280,10000,1.0,0,0,4,7,1280,0,1954,0,98006,47.5716,-122.139,1240,10000
2476,2477,195,3,1.5,1320,7201,1.0,0,0,3,7,1320,0,1971,0,98034,47.7126,-122.211,1380,7201
13548,13549,214,4,1.0,2180,10617,1.5,0,0,3,7,2180,0,1950,0,98155,47.7522,-122.307,1360,9519

In [56]:
X_test_single = X_test.iloc(0)

X_test_single = X_test.iloc[[0]]
X_test_single.shape

print(model.predict(X_test_single))

[203942.73829309]

In [58]:
# r2 value
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)

print(r2)

0.6946361707615893

In [59]:
# Step 8 : model accuracy
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error, mean_squared_error

mean_absolute_error(y_test,y_pred)

126063.94774521621

In [60]:
mean_squared_error(y_test,y_pred)

41852518118.55382